### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by 18720060819** [genericmoniker/onenote-dump#9]
![image](https://user-images.githubusercontent.com/58896750/189537078-293f7ffe-c31d-4529-bdf4-acc88b16ea5f.png)
通过你的代码生产两个文件夹，一个notes，一个attachments，notes的md文件夹的图片的markdown语言为@attachment

**Comment by renyuanzhe** [comment]
兄弟，你解决了吗

**Comment by 18720060819** [comment]
> 兄弟，你解决了吗

如果想把onenote改成markdown，建议直接使用OneNoteMdExporter软件，下载链接如下:
https://www.lanzouw.com/iYyWKxf6loj
